name: generate metrics

on:
  # run automatically every day
  schedule:
    - cron: "0 6 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main
    
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{secrets.ACCESS_TOKEN}}